FROM python:3.11
# We are using a python image of version 3.11

WORKDIR /code
# Creating our WORKDIR as /code

COPY . /code
# Copy everything in current directory(.) to /code

RUN pip install -r requirements.txt
# We don't need /code/requriements.txt since our workdir is /code

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
# The last command is always the CMD command
# host: 0.0.0.0 means current host
# port used is: 8000